name: "cristianounix"

description: "Fluid, responsive blog theme for Jekyll"

author: "Cristiano S. Oliveira - cristianounix"

url: "http://cristianounix.github.io/"
baseurl: ""

author-bio: "I am developer"

twitter: cristianounix
github: cristianounix
dribbble: cristianounix
instagram: cristianounix
facebook: cristianounix


markdown: kramdown
permalink: pretty
highlighter: pygments

exclude: ['vendor']
