name: "cristianounix"

description: "Fluid, responsive blog theme for Jekyll"

author: "Cristiano S. Oliveira - cristianounix"

url: "http://127.0.0.1:4000/"
baseurl: ""

author-bio: "I am developer"

twitter: cristianounix
github: cristianounix
dribbble: cristianounix
instagram: cristianounix
facebook: cristianounix


markdown: kramdown
permalink: pretty
highlighter: pygments
exclude: ['vendor']

# Permalinks
#permalink:        /blog/:year/:month/:day/:title

# Disqus
disqushandler: 'testingblogo'

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/