# Site settings
title: CristianoUnix
email: cristianounix@gmail.com
description: "....."
baseurl: "http://cristianounix.com.br"
url: "http://cristianounix.com.br"

# Build settings
markdown: kramdown
permalink: pretty
